---
title: "Codebook"
author: "Yineng Chen"
date: "2020/5/31"
output: html_document
---

# Human Activity Recognition Using Smartphones Data Set

## Data Set Information:

# Data Description

The data were collected from the accelerometers from the Samsung Galaxy S smartphone. 30 volunteers aged from 19 to 48 years were asked to perform six activities wearing a smartphone (Samsung Galaxy S II) on the waist.70% of the volunteers was selected for generating the training data and 30% the test data. For each volunteer, 561 features were recorded.  

A full description is available at the site where the data was obtained: click [here](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones)


The dataset includes the following files:
=========================================


- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'features.txt': List of the names of 561 features.

- 'activity_labels.txt': Links the class labels with their activity name.

- 'train/X_train.txt': Training set.

- 'train/y_train.txt': Training labels.

- 'test/X_test.txt': Test set.

- 'test/y_test.txt': Test labels.

- 'subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

- 'subject_test.txt': Each row identifies the subject who performed the activity for each window sample.

Activity_labels
=========================

1. WALKING

1. WALKING_UPSTAIRS

1. WALKING_DOWNSTAIRS

1. SITTING

1. STANDING

1. LAYING


Features of interest
========================

Only the measurements on the mean and standard deviation for each measurement were extracted. These measurements contain "mean()" and "std()" in their names. For example: "tBodyAcc-mean()-X","tBodyAcc-std()-Y".


